# Generated by Django 2.0.6 on 2019-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPostApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostmodel',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
